# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: site_development

  username: site_dev
  password: sergey228
  host: localhost
  port: 5432

test:
  <<: *default
  database: site_test
  host: localhost
  port: 5432
  username: site_dev
  password: sergey228
production:
  <<: *default
  database: blog_production
  username: blog_dev
  password: <%= ENV['SITE_DATABASE_PASSWORD'] %>